### ISSUE TITLE
Weak Documentation

### ISSUE THREAD

**Issue by JavaMachine** [sumeko/phalcon-oauth2-server#8]
Hi dear fellow developers...

I just copied and pasted files into my server and when I run it it gives me an error:

"Fatal error: Class 'League\OAuth2\Server\AuthorizationServer' not found in W:\domains\localhost\po\src\Phalcon\Oauth2\Server\StandaloneWrapper.php on line 35"

Should I add additional namespace?:

registerNamespaces([
    'Sumeko' => APP_PATH . '/../src/',
    'League' => APP_PATH . '/../oauth2-server/src/', //?????? is this correct?
])->register();

**Comment by nueko** [comment]
Hi,

That’s meant the depedant library not installed yet.

I implement my lib with git submodule and/or composer,

you can install the library needed with

git submodule init && git submodule update

or 

composer update

Regards

Dari: Javokhir
Dikirim: ‎Minggu‎, ‎23‎ ‎Agustus‎ ‎2015 ‎0‎:‎37
Kepada: sumeko/phalcon-oauth2-server

Hi dear fellow developers...

I just copied and pasted files into my server and when I run it it gives me an error:

"Fatal error: Class 'League\OAuth2\Server\AuthorizationServer' not found in W:\domains\localhost\po\src\Phalcon\Oauth2\Server\StandaloneWrapper.php on line 35"

Should I add additional namespace?:

registerNamespaces([
'Sumeko' => APP_PATH . '/../src/',
'League' => APP_PATH . '/../oauth2-server/src/', //?????? is this correct?
])->register();

**Comment by JavaMachine** [comment]
Thank you for your answer....

for now I have solved problem with including:

include  $_SERVER['DOCUMENT_ROOT']."/oauth2-server/src/AuthorizationServer.php";

the php class file...

The problem is now I am adding "include" where it cannot find class :(

is it ok if I use "include" ?

**Comment by JavaMachine** [comment]
I removed everything and started from scratch...

cloned as it was mentioned in readme.md....

after that I got error:

"Not-Found handler is not callable or is not definedW:\domains\localhost\public\index.php540"

then I added 
![image](https://cloud.githubusercontent.com/assets/5568121/9438031/49b4800e-4a74-11e5-8089-5143e6dafc47.png)

which solved that problem... but then I again returned to error:
"Fatal error: Class 'League\OAuth2\Server\AuthorizationServer' not found in W:\domains\localhost\src\Phalcon\Oauth2\Server\StandaloneWrapper.php on line 35"

As you see problem is still there :(

What should I do? 
Thanks in advance...

**Comment by JavaMachine** [comment]
Seems I solved problem with composer...

If anyone stuck with this problem, create "composer.json" file in the root of your project dir... and using console execute "composer update" or "php composer.phar update"...

{
    "require": {
        "league/oauth2-server": "*"
    }
}

And now I am facing usage problems....
My request:
![image](https://cloud.githubusercontent.com/assets/5568121/9438955/f3ce9a3c-4a7b-11e5-92f7-640113169d61.png)

and the response from server is: 
![image](https://cloud.githubusercontent.com/assets/5568121/9438975/1f527020-4a7c-11e5-99ce-988603e73287.png)

What Am I doing wrong??? could you please share usage examples :(
Thanks in advance

**Comment by tbjers** [comment]
What version of Phalcon are you using?

I can post a usage example tomorrow or later tonight if I get to it. I've
got this package running in production and it's been flawless.

**Comment by JavaMachine** [comment]
Thank you for your answer tbjers...

I am using phalcon 2.0.7 :)

Big thanks for your efforts :) It would be very helpful to me and to my project :)

**Comment by tbjers** [comment]
Hmm. I haven't tried this with the 2.x versions. My production environment
is still 1.3.x. I'll try to do a tutorial tomorrow (today, but I'm still
up) for 2.x for you.

**Comment by JavaMachine** [comment]
Looking forward tutorials from you :)

**Comment by nueko** [comment]
Hi again,

I love to help you but i have something else to do this week.

if you in hurry, you can use this library anyway 

bshaffer/oauth2-server-php

Dikirim dari Windows E-mail

Dari: Javokhir
Dikirim: ‎Selasa‎, ‎25‎ ‎Agustus‎ ‎2015 ‎16‎:‎07
Kepada: sumeko/phalcon-oauth2-server
Cc: Sum

Looking forward tutorials from you :)

**Comment by JavaMachine** [comment]
IMHO I implemented oauth2 into my project... but the problem is that when I try to authorize:
using link - localhost/authorize?grant_type=password&client_id=testclient&client_secret=secret
returning me invalid client_id... but in DB there is client with ID = testclient and SECRET KEY = secret

and why it is not asking me Username and password... ?

Thanks in advance...

**Comment by nueko** [comment]
try the develop branch and let me know, also please submit the related issue.
